# Transparency & Blur
background_blur 32

# Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 15

# Catppuccin Mocha Colors

# Colors

# Padding and appearance
window_padding_width 10
hide_window_decorations yes

# Neovide-style cursor trail
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# >>> themely colors
background #191f29
foreground #d3ddee
selection_background #547dc5
selection_foreground #191f29
cursor #547dc5
cursor_text_color #191f29
color0 #303b50
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #547dc5
color5 #f5c2e7
color6 #94e2d5
color7 #90a9d5
color8 #4d5f80
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #54acc5
color13 #f5c2e7
color14 #94e2d5
color15 #d3ddee
color16 #5457c5
color17 #2b3058
color18 #547dc5
color19 #2b3b58
color20 #54acc5
color21 #2b4958
dynamic_background_opacity yes
background_opacity 0.85
# <<< themely
