# Transparency & Blur
background_blur 32

# Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 15

# Catppuccin Mocha Colors

# Colors

# Padding and appearance
window_padding_width 10
hide_window_decorations yes

# Neovide-style cursor trail
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# >>> themely colors
background #29271a
foreground #eeebd3
selection_background #c4c0a2
selection_foreground #29271a
cursor #c4c0a2
cursor_text_color #29271a
color0 #4e4b31
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #c4c0a2
color5 #f5c2e7
color6 #94e2d5
color7 #d5cd90
color8 #7d774f
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #c4b2a2
color13 #f5c2e7
color14 #94e2d5
color15 #eeebd3
color16 #bdc4a2
color17 #555643
color18 #c4c0a2
color19 #585543
color20 #c4b2a2
color21 #585143
dynamic_background_opacity yes
background_opacity 0.85
# <<< themely
