[main]
font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes
prompt=" "
icon-theme=Papirus-Dark
layer=overlay
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=10

[colors]
# >>> themely colors
background=291919d9
text=eed3d3ff
match=ff1a1bff
selection=503030ff
selection-text=eed3d3ff
border=ff1a1bff
# <<< themely

[border]
width=2
radius=15
