[main]
font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes
prompt=" "
icon-theme=Papirus-Dark
layer=overlay
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=10

[colors]
# >>> themely colors
background=191f29d9
text=d3ddeeff
match=89b4faff
selection=303c50ff
selection-text=d3ddeeff
border=89b4faff
# <<< themely

[border]
width=2
radius=15
