[main]
font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes
prompt=" "
icon-theme=Papirus-Dark
layer=overlay
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=10

[colors]
# >>> themely colors
background=29271ad9
text=eeebd3ff
match=c4c0a2ff
selection=4e4b31ff
selection-text=eeebd3ff
border=c4c0a2ff
# <<< themely

[border]
width=2
radius=15
